services:
  mysql:
    image: mysql:8.0
#    restart: always
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=likelion
      - MYSQL_DATABASE=likelion
      - MYSQL_USER=likelion
      - MYSQL_PASSWORD=likelion
  adminer:
    image: adminer
    restart: always
    ports:
      - "3080:8080"